### ISSUE TITLE
Create UserResource services

### ISSUE THREAD

**Issue by dima-fedotovs** [JavaIIPlus01/service-reservation-system#7]
Create services for managing user:

* create user (registration)
* get list of users
* get single user by id
* update user

see [User management API](https://github.com/JavaIIPlus01/service-reservation-system/wiki/UserManagement) for reference

**Comment by yekaterinasavelyeva** [comment]
https://github.com/JavaIIPlus01/service-reservation-system/issues/18
Seems like our API has to be updated, as user role is client now.
